language: android

jdk:
- oraclejdk8

script: 
- ./gradlew assembleRelease --stacktrace

android:
  components:
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
  - tools
  - platform-tools
  licenses:
  - '.+'

sudo: required

install: true

before_script:
- chmod +x gradlew


